<h1><?php echo $this->escapeHtml($this->title) ?></h1>
<p>
    <a href="<?php echo $this->urlAdd ?>">Novo setor</a>
</p>

<table class="table">
    <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>&nbsp;</th>
    </tr>
    <?php
        echo $this->partialLoop('setores.phtml', $this->paginator);
    ?>
</table>
<p>
    <?php
        echo $this->paginationControl($this->paginator, 'Sliding', 'pagination', array('route' => 'setor'));
    ?>
</p>
<p>
    <a href="<?php echo $this->urlHomePage ?>">Homepage</a>
</p>