<?php
    $title = 'Setores';
    $this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title) ?></h1>

<p>
    <a href="<?php echo $this->url('setor', array('action' => 'add')) ?>">Novo setor</a>
</p>

<table class="table">
    <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($this->setores as $setor): ?>
            <tr>
                <td><?php echo $setor->codigo ?></td>
                <td><?php echo $setor->nome ?></td>
                <td>
                    <a href="<?php echo $this->url('setor', array('action' => 'edit', 'codigo' => $setor->codigo)) ?>">Editar</a>
                    <a href="<?php echo $this->url('setor', array('action' => 'delete', 'codigo' => $setor->codigo)) ?>">Remover</a>
                </td>
            </tr>
    <?php endforeach; ?>
</table>