<tr>
    <td><?php echo $this->lanterna->codigo; ?></td>
    <td><?php echo $this->escapeHtml($this->lanterna->nome); ?></td>
    <td><?php echo $this->escapeHtml($this->lanterna->setor); ?></td>
    <td>
        <a href="<?php echo $this->placeholder('url')->edit . $this->lanterna->codigo ?>">Editar</a> |
        <a href="<?php echo $this->placeholder('url')->delete . $this->lanterna->codigo ?>">Excluir</a>
    </td>
</tr>