<tr>
    <td><?php echo $this->model->codigo; ?></td>
    <td><?php echo $this->escapeHtml($this->model->nome); ?></td>
    <td><?php echo $this->escapeHtml($this->model->setor); ?></td>
    <td>
        <a href="<?php echo $this->placeholder('url')->edit . '/' . $this->model->codigo ?>">Editar</a> |
        <a href="<?php echo $this->placeholder('url')->delete . '/' . $this->model->codigo ?>">Excluir</a>
    </td>
</tr>