<h1><?php echo $this->escapeHtml($this->title) ?></h1>
<p>
    <a href="<?php echo $this->urlAdd ?>">Novo lanterna</a>
</p>
<table class="table">
    <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>Setor</th>
        <th>&nbsp;</th>
    </tr>
    <?php echo $this->partialLoop('lanternas.phtml', $this->paginator) ?>
</table>
<p>
    <?php
        echo $this->paginationControl($this->paginator, 'Sliding', 'pagination', array('route' => 'lanterna'));
    ?>
</p>
<p>
    <a href="<?php echo $this->urlHomepage ?>">Homepage</a>
</p>