<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle() ?>
    </head>
    <body>
        <div class="container">
            <header>
                <p>Sistema de controle da tropa dos lanternas verdes</p>
            </header>
            <?php echo $this->content ?>
            <hr>
            <footer>
                <p>
                    &copy; 2013 by oa. <?php echo $this->translate('All rights reserved') ?>
                </p>
            </footer>
        </div>
    </body>
</html>
